### ISSUE TITLE
Can't compile on OS X 10.9.3

### ISSUE THREAD

**Issue by houbysoft** [mattjj/pyhsmm#23]
Hi,

I'm running into a similar issue as https://github.com/mattjj/pyhsmm/issues/21. I'm on OS X 10.9.3, and I'm using clang (Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)).

I tried building in two ways specified by the README but both failed for me.

First I tried:

$ python setup.py build_ext --inplace
running build_ext
gcc-4.2 not found, using clang instead
building 'internals.hmm_messages_interface' extension
clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -O2 -DNDEBUG -g -O3 -Ideps/Eigen3/ -I/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c internals/hmm_messages_interface.cpp -o build/temp.macosx-10.6-intel-2.7/internals/hmm_messages_interface.o -O3 -w -DNDEBUG -std=c++11 -DHMM_TEMPS_ON_HEAP
In file included from internals/hmm_messages_interface.cpp:360:
In file included from internals/hmm_messages.h:4:
In file included from deps/Eigen3/Eigen/Core:287:
deps/Eigen3/Eigen/src/Core/MathFunctions.h:357:18: error: no member named
      'log1p' in namespace 'std'; did you mean 'log10'?
      using std::log1p;
            ~~~~~^~~~~
                 log10
... bunch of other errors follow ...

I also tried the suggested alternative for clang but got:
$ python setup.py build_ext --inplace --with-old-clang
running build_ext
gcc-4.2 not found, using clang instead
building 'internals.hmm_messages_interface' extension
clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -O2 -DNDEBUG -g -O3 -Ideps/Eigen3/ -I/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c internals/hmm_messages_interface.cpp -o build/temp.macosx-10.6-intel-2.7/internals/hmm_messages_interface.o -O3 -w -DNDEBUG -std=c++11 -DHMM_TEMPS_ON_HEAP -stdlib=libc++
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
error: command 'clang' failed with exit status 1

Any ideas?

Thanks
